{
 "title": "Heatmaps",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Prom heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Prom - multiple metrics",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cdm_heat_map_metric_bucket_10", "legendFormat": "{{__name__}}" },
    { "expr": "cdm_heat_map_metric_bucket_15", "legendFormat": "{{__name__}}" },
    { "expr": "cdm_heat_map_metric_bucket_20", "legendFormat": "{{__name__}}" },
    { "expr": "cdm_heat_map_metric_bucket_5", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Influx heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heat_map_metric",
     "query": "SELECT mean(/bucket_*/) FROM \"autogen\".\"heat_map_metric\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bucket_10" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Influx Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "static_metric",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}