version: '3'
services:
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
      # prometheus-client is configured to expose the metrics on localhost:9273 
      - "9273:9273"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # Not in use
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  otel-collector:
    # The "raw" image that has only "core" features (https://github.com/open-telemetry/opentelemetry-collector)
    #image: otel/opentelemetry-collector
    # The "contrib" image has all of the custom receivers/exporters present (https://github.com/open-telemetry/opentelemetry-collector-contrib)
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 19000:19000 # Influx receiver
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector itself
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
