scrape_configs:
  # Enable this to scrape from OTelCollector (Exporter)
  - job_name: 'otel-collector'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8889']

  # Enable this to scrape from Telegraf (Output plugin)
  - job_name: 'telegraf-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9273']

  # Enable this to scrape from Graphite-Exporter
  - job_name: 'graphite-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9108']

  # Enable this to scrape from Push gateway
  - job_name: 'push gateway'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9091']
